### ISSUE TITLE
WP theme unable to login

### ISSUE THREAD

**Issue by jxm90** [mudmin/usthemes#2]
I've tried a few themes, I get "There was an error with your form. Please go back and try again. Please note that submitting the form by refreshing the page will cause an error. If this continues to happen, please contact the administrator." when trying to login.

**Comment by jxm90** [comment]
How would I change the theme back to standard from within the database, where would I find that info? Thanks!

**Comment by Brandin** [comment]
> There was an error with your form. Please go back and try again. Please note that submitting the form by refreshing the page will cause an error. If this continues to happen, please contact the administrator.

This is related to the CSRF token and likely due to invalidating the token on the form by opening it more than once and using an old form, or for other purposes. I don't suspect this is in specific to any theme, but if you can provide more details, we'll look more closely. Please join our Discord and seek support there. Issues on the GitHub Repos are generally not monitored.

https://discord.gg/j25FeHu

Thank you,
Brandin.
